"use client";
import React from "react";
import Navbar from "@Components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@Components/Footer";
import { useState } from "react";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showConversion, setShowConversion] = useState(false);
  const [showCharts, setShowCharts] = useState(false);
  const [showHome, setShowHome] = useState(true);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-full bg-black w-full flex justify-between flex-col">
          <Navbar
            setShowConversion={setShowConversion}
            setShowCharts={setShowCharts}
            setShowHome={setShowHome}
            showHome={showHome}
            showCharts={showCharts}
            showConversion={showConversion}
          />
          <Home
            showHome={showHome}
            showCharts={showCharts}
            showConversion={showConversion}
          />
          <Footer />
        </main>
      </body>
    </html>
  );
}
